# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [47]:
# LOADING THE DATA
df = pd.read_csv(r"C:\Users\user\Documents\Moringa Data Science\Flatiron\LABS\End of Module Summative labs\M2\dsc-course0-m8-lab\data\AviationData.csv", encoding='cp1252')
df.head()

C:\Users\user\AppData\Local\Temp\ipykernel_12388\1229957997.py:2: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\user\Documents\Moringa Data Science\Flatiron\LABS\End of Module Summative labs\M2\dsc-course0-m8-lab\data\AviationData.csv", encoding='cp1252')

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [48]:
# inspect NaNs
df.isna().sum()[df.isna().sum() > 0]

Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [49]:
#datatypes
df.dtypes

Event.Id                   object
Investigation.Type         object
Accident.Number            object
Event.Date                 object
Location                   object
Country                    object
Latitude                   object
Longitude                  object
Airport.Code               object
Airport.Name               object
Injury.Severity            object
Aircraft.damage            object
Aircraft.Category          object
Registration.Number        object
Make                       object
Model                      object
Amateur.Built              object
Number.of.Engines         float64
Engine.Type                object
FAR.Description            object
Schedule                   object
Purpose.of.flight          object
Air.carrier                object
Total.Fatal.Injuries      float64
Total.Serious.Injuries    float64
Total.Minor.Injuries      float64
Total.Uninjured           float64
Weather.Condition          object
Broad.phase.of.flight      object
Report.Status              object
Publication.Date           object
dtype: object

In [50]:
# summary statistics
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [51]:
#After this filtering, the dataset will contain:

#only professional aircraft
#only valid accident records
#only 1983–2023 events
#only usable Make/Model data

In [52]:
#inspect relevant columns
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

In [53]:
#Convert Dates to date data type and then filter df to only filter from the year 1983
df["Event.Date"] = pd.to_datetime(df["Event.Date"], errors="coerce")
#Creating a year column
df["Year"] = df["Event.Date"].dt.year
#Filter dataset (1983 onwards ONLY)
df = df[df["Year"] >= 1983]

In [54]:
# Keep only relevant aircraft records
df = df.dropna(subset=["Make", "Model", "Aircraft.damage"])

In [55]:
#Keep only professional builds
df = df[df["Amateur.Built"] == "No"]

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [56]:
# removing missing values first.
df["Total.Fatal.Injuries"] = df["Total.Fatal.Injuries"].fillna(0)
df["Total.Serious.Injuries"] = df["Total.Serious.Injuries"].fillna(0)
df["Total.Minor.Injuries"] = df["Total.Minor.Injuries"].fillna(0)
df["Total.Uninjured"] = df["Total.Uninjured"].fillna(0)

In [57]:
# Estimating total passengers onboard (Total On Board=Fatal+Serious+Minor+Uninjured)
df["Total.On.Board"] = (
    df["Total.Fatal.Injuries"] +
    df["Total.Serious.Injuries"] +
    df["Total.Minor.Injuries"] +
    df["Total.Uninjured"]
)

In [58]:
# Removing invalid flights (Total.On.Board < 0)
df = df[df["Total.On.Board"] > 0]

In [59]:
# Constructing Fatal Injury likelihood metric(Fatal Injury Likelihood= Total Fatal Injuries/Total On Board )
df['Fatal.Injury.Likelihood'] = (
    df['Total.Fatal.Injuries'] / df['Total.On.Board']
)

In [60]:
# Construct Serious Injury likelihood metric (Serious Injury Likelihood=Total Serious Injuries/Total On Board)

df["Serious.Injury.Likelihood"] = (
    df["Total.Serious.Injuries"] / df["Total.On.Board"]
)

In [61]:
# Combined risk score Total Injury Risk=  (Fatal + Serious Injuries)/Total On Board
df["Severe.Injury.Risk"] = (
    df["Total.Fatal.Injuries"] +
    df["Total.Serious.Injuries"]
) / df["Total.On.Board"]

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [62]:
#inspecting values 
df["Aircraft.damage"].value_counts(dropna=False)

Aircraft.damage
Substantial    55412
Destroyed      15366
Minor           2296
Unknown           89
Name: count, dtype: int64

In [63]:
# standardize text formart for consistency
df["Aircraft.damage"] = df["Aircraft.damage"].str.lower().str.strip()

In [64]:
# Create “Destroyed Aircraft” column by converting damage into a binary safety metric. 1 = aircraft destroyed and 0 = not destroyed
df["Aircraft.Destroyed"] = df["Aircraft.damage"].apply(
    lambda x: 1 if x == "destroyed" else 0
)

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [65]:
# Inspect the column first
df["Make"].value_counts(dropna=False).head(30)

Make
Cessna               20670
Piper                11183
CESSNA                4744
Beech                 4000
PIPER                 2765
Bell                  1954
Mooney                1024
BEECH                 1003
Grumman                979
Boeing                 922
Robinson               907
Bellanca               816
Hughes                 730
Schweizer              602
Air Tractor            576
BELL                   551
Aeronca                455
Maule                  425
Champion               411
BOEING                 384
Mcdonnell Douglas      361
Aero Commander         338
De Havilland           333
Stinson                330
Rockwell               312
Taylorcraft            303
Luscombe               294
Hiller                 291
North American         290
Aerospatiale           287
Name: count, dtype: int64

### Cleaning tasks for Make column

- Converted all values to lowercase for consistency
- Stripped leading and trailing whitespace
- Removed missing values (Make is essential for grouping aircraft)
- Standardized manufacturer names implicitly through grouping (e.g., Boeing variants treated as one group later)
- Filtered out rare manufacturers with low sample sizes (less than 50 occurrences) to ensure statistical reliability

In [66]:
# Standardize text
df["Make"] = df["Make"].str.lower().str.strip()

In [67]:
# Remove missing values
df = df.dropna(subset=["Make"])

In [68]:
# FIlter by sample size (Requirement) - keep only manufacturers with enough data (≥ 50 accidents)
make_counts = df["Make"].value_counts()

valid_makes = make_counts[make_counts >= 50].index

df = df[df["Make"].isin(valid_makes)]

In [69]:
# check outcome
df['Make'].head(20)

3601            cessna
3602            cessna
3603            cessna
3604             piper
3605            cessna
3607            cessna
3608    north american
3609             piper
3610             piper
3611             beech
3612             beech
3613            cessna
3614            cessna
3615            cessna
3616        swearingen
3617            cessna
3618            cessna
3619             piper
3620          canadair
3621             piper
Name: Make, dtype: object

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [70]:
#Inspect the Model column
df["Model"].value_counts(dropna=False).head(30)

Model
152          2212
172          1616
172N         1080
PA-28-140     858
172M          757
150           742
172P          661
182           609
180           595
150M          550
PA-18-150     547
PA-28-180     546
PA-18         546
PA-28-161     519
PA-28-181     502
206B          479
150L          432
A36           421
G-164A        421
PA-38-112     419
140           383
170B          374
G-164B        363
172S          360
206           359
R44           339
PA-32-300     335
182P          332
PA-24-250     328
269C          322
Name: count, dtype: int64

In [71]:
#check missing values
df["Model"].isna().sum()

0

In [72]:
#Remove missing values - none 
df = df.dropna(subset=["Model"])

In [73]:
#Standardize formatting
df["Model"] = df["Model"].str.lower().str.strip()

In [74]:
# Are model labels unique to each make? - No they are not unique
df.groupby("Model")["Make"].nunique().sort_values(ascending=False).head(20)

Model
500       7
g-164a    7
g-164b    6
g-164     5
g-164c    5
690a      4
7ec       4
269c      4
aa-5      4
g164-b    4
112       4
8kcab     4
aa-5b     4
300       4
7eca      4
s-2r      4
690b      4
700       4
600       4
s2r       4
Name: Make, dtype: int64

In [75]:
# combine Make + Model - to create a unique identifier
df["Aircraft.ID"] = df["Make"] + "_" + df["Model"]

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [76]:
# cleaning Engine.Type
df["Engine.Type"] = df["Engine.Type"].str.lower().str.strip()

In [77]:
# cleaning Weather.Condition
df["Weather.Condition"] = df["Weather.Condition"].str.lower().str.strip()

In [78]:
# cleaning Number.of.Engines
df["Number.of.Engines"] = pd.to_numeric(df["Number.of.Engines"], errors="coerce")

In [79]:
#cleaning Purpose.of.flight
df["Purpose.of.flight"] = df["Purpose.of.flight"].str.lower().str.strip()

In [80]:
# Cleaning Broad.phase.of.flight
df["Broad.phase.of.flight"] = df["Broad.phase.of.flight"].str.lower().str.strip()

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [81]:
# check missing values per column
missing_pct = df.isnull().mean().sort_values(ascending=False) * 100
missing_pct

Schedule                     86.869939
Air.carrier                  82.679494
FAR.Description              70.698258
Aircraft.Category            70.493591
Longitude                    62.781977
Latitude                     62.773014
Airport.Code                 42.349637
Airport.Name                 39.626221
Broad.phase.of.flight        27.232663
Publication.Date             17.230870
Engine.Type                   5.903971
Report.Status                 5.528997
Number.of.Engines             5.010607
Purpose.of.flight             4.971765
Weather.Condition             3.320984
Registration.Number           1.272820
Country                       0.267412
Location                      0.052287
Year                          0.000000
Total.Uninjured               0.000000
Severe.Injury.Risk            0.000000
Fatal.Injury.Likelihood       0.000000
Aircraft.Destroyed            0.000000
Serious.Injury.Likelihood     0.000000
Total.On.Board                0.000000
Event.Id                      0.000000
Total.Minor.Injuries          0.000000
Total.Serious.Injuries        0.000000
Total.Fatal.Injuries          0.000000
Investigation.Type            0.000000
Amateur.Built                 0.000000
Model                         0.000000
Make                          0.000000
Aircraft.damage               0.000000
Injury.Severity               0.000000
Event.Date                    0.000000
Accident.Number               0.000000
Aircraft.ID                   0.000000
dtype: float64

In [82]:
# Dropping all the columns that have missing_pct > 70%
df = df.drop(columns=[
    "Schedule",
    "Air.carrier",
    "FAR.Description",
    "Aircraft.Category"
])

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [83]:
# save the cleaned data frame
df.to_csv("aviation_cleaned_data.csv", index=False)

In [84]:
# checking if saved
import os

os.listdir()

['.git',
 '.gitkeep',
 '.ipynb_checkpoints',
 'Aviation_Accidents_Cleaning.ipynb',
 'Aviation_Accidents_Data_Analysis.ipynb',
 'aviation_cleaned_data.csv',
 'data',
 'LICENSE',
 'README.md']